### ISSUE TITLE
Bulk Executor BulkUpdateAsync stopped working with error 'Variable undefined in strict mode'

### ISSUE THREAD

**Issue by MNaveedKhalid** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#16]
I'm using bulk executor library for some time and it worked fine. Suddenly from today it started throwing an error without any changes in the code. Looks some thing changed on server system stored procedures.
Here is error:
Operation will NOT be retried. Current attempt 0, Exception: Microsoft.Azure.Documents.BadRequestException: Message: {"Errors":["Encountered exception while executing function. Exception = ReferenceError: Variable undefined in strict mode\r\nStack trace: ReferenceError: Variable undefined in strict mode\n   at handleUpdate (AddComponent.js:5008:17)\n   at processOneResult (AddComponent.js:4982:29)\n   at queryCallback (AddComponent.js:4960:21)\n   at Anonymous function (AddComponent.js:608:29)"]}

**Comment by MNaveedKhalid** [comment]
I have tried the sample, this also has same error in bulk update. Please verify.

**Comment by abinav2307** [comment]
Hi all,

Sincere apologies for the delayed response. We rolled out a fix for this in September 2018 and this issue has been resolved.

Please re-open this issue if anyone is still running into this problem. We have also rolled out multiple versions of the BulkExecutor since, with the most recent version (1.4.1) here- https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/
