### ISSUE TITLE
BulkExecutor 2.0.0-preview2 compatible with DocumentDB(.Core) 2.2.0?

### ISSUE THREAD

**Issue by galmok** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#31]
If I include DocumentDB(.Core) 2.2.0, then I get the following warning when also including BulkExecutor 2.0.0-preview2:

Detected package version outside of dependency constraint: Microsoft.Azure.CosmosDB.BulkExecutor 2.0.0-preview2 requires Microsoft.Azure.DocumentDB.Core (= 2.1.3) but version Microsoft.Azure.DocumentDB.Core 2.2.0 was resolved.

If I use the BulkExecutor, will it be safe to use DocumentDB 2.2.0 or must I use Document 2.1.3?

**Comment by rifuller** [comment]
I'm seeing a missing method error in InitializeAsync() when using Microsoft.Azure.DocumentDB.Core 2.2.1 and Microsoft.Azure.DocumentDB.BulkExecutor 2.1.0-preview2.

Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync

I think they're incompatible. Going to test with M.Azure.DocumentDB.Core 2.1.3.

**Comment by rifuller** [comment]
Confirming that using M.Azure.DocumentDB.Core 2.1.3 works when 2.2.0 didn't.

**Comment by galmok** [comment]
BulkExecutor 2.1.0-preview2 is now available, but it is still hard-referenced to DocumentDB(.Core) 2.1.3, even though there is now 3 newer releases it could be reference (2.2.0, 2.2.1, and 3.0.0.0-preview).

Also, there is no changelog for 2.1.0-preview2 yet:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-bulk-executor-dot-net

**Comment by abinav2307** [comment]
Hi all,

Apologies for the delay in responding. As @rifuller pointed out, this is a hard dependency in the present version of the BulkExecutor due to internal dependencies.

We are looking to see if some of these internal dependencies can be resolved in subsequent release of the BulkExecutor.

In addition, we are also working on a batch API which will be internal to our SDK as well, eliminating the need for multiple libraries in the near future.
