### ISSUE TITLE
Error: The \"docs\" parameter must be an array on 'BulkImportAsync'

### ISSUE THREAD

**Issue by mkravchuk7** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#33]
Getting the following error when performing 'BulkImportAsync':

> "Microsoft.Azure.Documents.DocumentClientException : Partition range id 0 | Failed to import mini-batch. Exception was Message: {"Errors":["Encountered exception while executing function. Exception = Error: The \"docs\" parameter must be an array. Got \"object\".

This is strange because array of poco objects is passed as 'docs' param according to documentation. 
Quote from [official docs](https://docs.microsoft.com/ru-ru/azure/cosmos-db/bulk-executor-dot-net#bulk-import-data-to-azure-cosmos-db):

> "5. The application invokes the BulkImportAsync API. The .NET library provides two overloads of the bulk import API - one that accepts a list of serialized JSON documents and the other accepts a list of deserialized POCO documents."

BTW the second overload that accepts IEnumerable of strings also throws the same error.

**Version used:** 2.1.0-preview2

**Comment by mkravchuk7** [comment]
BTW we get this same error even when using second overload of 'BulkImportAsync' that accepts 'IEnumerable<string>' as docs param.

**Comment by abinav2307** [comment]
Hello @mkravchuk7, the Bulk Executor performs certain translations under the hood and thus the IEnumerable of documents is deserialized into an object of a different type. Because the source and destination types aren't the same, using "Auto" TypeNameHandling is always going to deserialize the IEnumerable input into a single object with "type" and "value" specified. This changes the expected object in the internal implementation of the BulkExecutor library, leading to this error.

In this scenario, it is recommended to not have a custom serializer for the DocumentClient object being used to instantiate the BulkExecutor.

**Comment by mkravchuk7** [comment]
So if I pass **valid**  'JsonSerializerSettings' on 'DocumentClient' creation and use Bulk Executor it will throw some cryptic error? I see that internal implementation doesnt permit this setting but how the client of this lib should know about this? Would be nice to at least have more descriptive error in this case.
