### ISSUE TITLE
BulkDeleteAsync Missing in 2.1.0

### ISSUE THREAD

**Issue by refractivSteve** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#35]
BulkDeleteAsync was added in 1.3.0 and is in 2.0.0 (preview 2) but is no longer available in 2.1.0 (preview 2).  Was this an accidental omission?

**Comment by abinav2307** [comment]
We recently noticed a bug in the query overload for BulkDelete, because of which it was removed in the latest version(s).

Currently, out BulkDelete only supports <Partition key, id> tuples as input.

However, we are working on a fix for the query overload as well and will add a sample as soon as the fix is released.

**Comment by abinav2307** [comment]
While we removed the query overload (also removed from IBulkExecutor), you can still use the BulkDeleteAsync() method using PartitionKey and documentId tuples, as shown in the sample here - https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started

**Comment by bcassell** [comment]
Is this coming back at some point?  What exactly is the bug?  I'm stuck using 2.0.0-preview2 because having to know all of the ids defeats my entire use case for this library 👎
