### ISSUE TITLE
Thanks. Any sample for bulkExecuter.BulkDeleteAsync

### ISSUE THREAD

**Issue by zaalion** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#37]
Hi,

Do you have any sample for bulkExecuter.BulkDeleteAsync?

Thanks,
Reza

**Comment by ogliznutsa** [comment]
Duplicate of https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started/issues/30

**Comment by cgelon** [comment]
The latest package (1.4.0) has changed the parameters of BulkDeleteAsync to be a List<Tuple<string, string>> of PartitionKey and ID (PartitionKey is first and ID of the document is second) and an optional integer of batch delete size; providing it with a list of tuples should now be pretty straightforward.

**Comment by abinav2307** [comment]
We recently noticed a bug in the query overload for BulkDelete, because of which it was removed in the latest version(s). 

Currently, out BulkDelete only supports <Partition key, id> tuples as input. 

However, we are working on a fix for the query overload as well and will add a sample as soon as the fix is released.

**Comment by abinav2307** [comment]
Updated the sample for .NET with BulkDelete here - https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started
