### ISSUE TITLE
"Failed to import mini-batch" Error

### ISSUE THREAD

**Issue by Toukiletoukan** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#8]
Hello,

Can you explain this kind of error message while trying to Bulk Update documents ?

The exact message of the exception is:

`Microsoft.Azure.Documents.DocumentClientException: Partition range id 5 | Failed to import mini-batch. Exception was A task was canceled.`

Thanks

**Comment by abinav2307** [comment]
Hello @Toukiletoukan, this messages indicates a failure while updating one of the chunks of the batch of updates sent to the BulkExecutor as input. The recommendation here is to simply retry the entire batch in the case of intermittent errors.

We are also working on pushing out changes soon to send back to the user, the specific subset of updates (or imports if running BulkImportAsync) that failed. This will then allow the user to simply retry the failed updates instead of the entire batch.
